<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ExamKiosk.Contracts\ExamKiosk.Contracts.csproj" />
    <ProjectReference Include="..\ExamKiosk.ProfileValidation\ExamKiosk.ProfileValidation.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
